title: SDG 01 and SDG 10
logo: https://cdn.stocksnap.io/img-thumbs/960w/grafitti-city_9ASLNGPUGM.jpg
description: This page contains the work in program for these two chapters of the SDG ATLAS 2020
show_downloads: true
theme: jekyll-theme-minimal
