---
title: "Growth Incidende Curve (GIC) of medians and GDP percapita"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    theme: paper
    source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library("here")
library("tidyverse")
library("data.table")
library("ggplot2")
library("plotly")
library("pins")
library("WDI")

#----------------------------------------------------------
#   subfunctions
#----------------------------------------------------------
# source(here("R", "utils.R"))


qtile <- function(x, nq = 10) {
  N   <-  length(x)
  csw <-  1:N
  qp  <-   floor(csw/((N+1)/nq)) + 1
  return(qp)
}


#----------------------------------------------------------
#   Aux data
#----------------------------------------------------------
my_key    <- Sys.getenv("connect_key")

# my_server <- "http://w0lxopshyprd1b.worldbank.org:3939/"
my_server  <- "http://localhost:3939/"

board_register_rsconnect(server = my_server,
                         key    = my_key)

dfc <- pin_get(name = "country_deciles",
               board = "rsconnect")

# dfc <- readr::read_rds(here("data", "dfc.rds"))


#----------------------------------------------------------
#   Calculate Quantiles
#----------------------------------------------------------

# set data.table

DT <- as.data.table(dfc)
setnames(DT, "threshold", "pv")


DT <- DT[
  # remove old years
  year >= 1990
][
  # filter negative values (which we should not have)
  pv > 0 & !is.na(pv)
][,
  # multiply by 100
  goal := 100*goal

][
  ,
  headcount := NULL
]


yrs <- DT[, unique(year)]


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#---------   GDP percapita    ---------
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# WDIsearch('gdp.*capita.*constant')
codes <- read_rds(here("data", "cty_regs_names.rds"))

iso <- WDI_data$country %>%
  as_tibble() %>%
  select(countrycode = iso3c,iso2c) %>%
  inner_join(codes, by = "countrycode")



# indicator = "NY.GDP.PCAP.KD"
indicator = "NY.GDP.PCAP.PP.KD"
gdp <-  WDI(indicator = indicator,
           start       = 1993,
           end         = 2017) %>%
  inner_join(iso, by = "iso2c") %>%
  mutate(gdp = get(indicator)/365)


GDP <- as.data.table(gdp)

GDP <- GDP[
  # remove old years
  year >= 1990
][
  # filter negative values (which we should not have)
  gdp > 0 & !is.na(gdp)
]

varlabel <- attributes(gdp[[indicator]])$label


```


Sidebar {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r}
sliderInput("pc", 
            label = "Percentile",
            min = 10, max = 100, value = 50, step = 10)

numericInput("nq", 
            label = "Number of quantiles",
            min = 5, max = 100, value = 10, step  = 5)

selectInput("yr1", 
            label    = "Year 1",
            choices  = yrs, 
            selected = 1993)

selectInput("yr2", 
            label    = "Year 2",
            choices  = yrs, 
            selected = 2017)

selectInput("ms", 
            label = "Measure:",
            choices = c("sum", "mean", "min", "max"),
            selected = "mean")

checkboxInput("an", 
              "Anonymous?", 
              value = TRUE)

checkboxInput("abs", 
              "Absolute Change", 
              value = FALSE)



```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### GIC of welfare from household surveys

```{r}

DQ <- reactive({
  
  calc <- paste0(".(", input$ms, "  = ", input$ms, "(pv, na.rm = TRUE))")
  calc <- parse(text = calc)
  
  # Make sure the input are included correclty in data.table (not efficient but works)
  iyr1  <- as.numeric(input$yr1)
  iyr2  <- as.numeric(input$yr2)
  yrdif <- iyr2 - iyr1
  yrst  <- c(iyr1, iyr2)

  DQ <-
    DT[
      year  %in% yrst
      & goal == input$pc
      ]
  
  setorder(DQ, year, pv)

  if (input$an == TRUE) {
    
    DQ <-
      DQ[
        , # Create deciles in each percentile
        qp := qtile(pv, input$nq),
        by = .(year)
      ]
    
  } else {
    
    QP <- DQ[year == input$yr1
            ][,
              qp := qtile(pv, input$nq)
            ][,
              c("countrycode", "coverage", "qp")
            ]
    
    DQ <- DQ[QP,
             on = .(countrycode, coverage)
             ]
    
  }
  
  DQ <- DQ[
    , # Make requested calculation
    eval(calc),
    by = .(year, qp)
    ][
      ,
      yr := ifelse(year == iyr1, "yr1", "yr2")
    ]
    
  
  DQ <- dcast(DQ,
              formula = qp ~ yr,
              value.var = input$ms)
  
  DQ <- DQ[,
           `:=`(
               gic = ((yr2/yr1)^(1 / yrdif)) - 1,
               abs = yr2 - yr1
             )
           ]
  
  DQ[,
     text := paste0("GIC: ", scales::percent(gic, accuracy = .01), "\n",
                    "Absolute change: ", scales::dollar(abs), "\n",
                    "value year 1: ", scales::dollar(yr1), "\n",
                    "value year 2: ", scales::dollar(yr2), "\n"
                    )]

  return(DQ)

})
```

```{r}
renderPlotly({
  
  if (input$abs == FALSE) {
    yvar = "gic"
    ylab = "scales::percent"
    ytit = "Annualized growth"
    titl = paste0("GIC of the quantile", input$ms ," of the distribution of the ",input$pc,"th percentile")
  } else {
    yvar = "abs"
    ylab = "scales::dollar"
    ytit = "Monetary change"
    titl = paste0("Total monetary change of the ", input$ms ," of the ",  input$pc,"th percentile")
  }
    
  
  pn <- ggplot(DQ(),
       aes(
         x    = qp,
         y    = get(yvar)
       )
          ) +
      geom_point(aes(text = text)) +
      geom_line() +
      geom_hline(yintercept = 0,
                 color = "red") +
      theme_minimal() +
      scale_y_continuous(labels = eval(parse(text = ylab))) +
      labs(
        title = titl,
        x     = "Quantiles",
        y     = ytit
      )

  ggplotly(pn, tooltip = "text")
})
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### GIC of GDP per capita

```{r}

DG <- reactive({
  
  
  calc <- paste0(".(", input$ms, "  = ", input$ms, "(gdp, na.rm = TRUE))")
  calc <- parse(text = calc)
  
  
  # Sort
  

  # Make sure the input are included correclty in data.table (not efficient but works)
  iyr1  <- as.numeric(input$yr1)
  iyr2  <- as.numeric(input$yr2)
  yrdif <- iyr2 - iyr1
  yrst  <- c(iyr1, iyr2)

  DG <-
    GDP[
      year  %in% c(input$yr1, input$yr2)
    ]
  
  setorder(DG, year, gdp)
  

  if (input$an == TRUE) {
    
    DG <-
      DG[
        , # Create deciles in each percentile
        qp := qtile(gdp, input$nq),
        by = .(year)
      ]
    
  } else {
    
    QP <- DG[year == input$yr1
            ][,
              qp := qtile(gdp, input$nq)
            ][,
              c("countrycode",  "qp")
            ]
    
    DG <- DG[QP,
             on = .(countrycode)
             ]
    
  }
  
  DG <- DG[
    , # Make requested calculation
    eval(calc),
    by = .(year, qp)
    ][
      ,
      yr := ifelse(year == iyr1, "yr1", "yr2")
    ]
    
  
  DG <- dcast(DG,
              formula = qp ~ yr,
              value.var = input$ms)
  
  DG <- DG[,
           `:=`(
               gic = ((yr2/yr1)^(1 / yrdif)) - 1,
               abs = yr2 - yr1
             )
           ]

  DG[,
     text := paste0("GIC: ", scales::percent(gic, accuracy = .01), "\n",
                    "Absolute change: ", scales::dollar(abs), "\n",
                    "value year 1: ", scales::dollar(yr1), "\n",
                    "value year 2: ", scales::dollar(yr2), "\n"
                    )]
  
  return(DG)
})
```

```{r}
renderPlotly({
  
  if (input$abs == FALSE) {
    yvar = "gic"
    ylab = "scales::percent"
    ytit = "Annualized growth"
    titl = paste0("GIC of the quantile", input$ms ," of ", varlabel)
  } else {
    yvar = "abs"
    ylab = "scales::dollar"
    ytit = "Monetary change"
    titl = paste0("Total monetary change of the ", input$ms ," of ", varlabel)
  }
    
  
  pn <- ggplot(DG(),
       aes(
         x = qp,
         y = get(yvar)
       )
          ) +
      geom_point(aes(text = text)) +
      geom_line() +
      geom_hline(yintercept = 0,
                 color = "red") +
      theme_minimal() +
      scale_y_continuous(labels = eval(parse(text = ylab))) +
      labs(
        title = titl,
        x     = "Quantiles",
        y     = ytit
      )

  ggplotly(pn, tooltip = "text")
})
```

