---
title: "Poverty projections considering COVID"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    theme: paper
    source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library("here")
library("ggplot2")
library("plotly")
library("flexdashboard")
library("hrbrthemes")


#----------------------------------------------------------
#   subfunction
#----------------------------------------------------------
addUnits <- function(n, d = 0) {
  labels <- ifelse(n < 1000, n,  # less than thousands
                   ifelse(n < 1e6, paste0(round(n/1e3, d), 'k'),  # in thousands
                          ifelse(n < 1e9, paste0(round(n/1e6, d), 'M'),  # in millions
                                 ifelse(n < 1e12, paste0(round(n/1e9, d), 'B'), # in billions
                                        'too big!')
                          )
                   )
  )
  return(labels)
}

#----------------------------------------------------------
#   DAta
#----------------------------------------------------------
source(here("R", "SDG_01_covid_projections.R"))

# Parameters
yrs <- DB[, unique(year)]
gsc <- DB[, unique(growth)]
pls <- DB[, unique(povline)]

```


Sidebar {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r}
selectInput("gr", 
            label    = "Growth Scenario",
            choices  = c("precovid", "baseline", "downside"), 
            selected = "precovid")

selectInput("yr", 
            label    = "Minimum Year",
            choices  = yrs, 
            selected = 2000)

selectInput("myr", 
            label    = "Maximum Year",
            choices  = yrs, 
            selected = 2030)

selectInput("pl", 
            label    = "Poverty Line",
            choices  = pls, 
            selected = "1.9")

selectInput("ms", 
            label    = "Measure",
            choices  = c("Poverty Rate", "Number of poor") , 
            selected = "Poverty Rate")


```

Column {data-width=1000 .tabset .tabset-fade}
-----------------------------------------------------------------------

### Poverty rate and number of poor projections

```{r}

DQ <- reactive({
  
  yr  <- as.numeric(input$yr) 
  
  DQ <-
    DB[growth    %chin% c("actual", input$gr)
       & year    %between% c(input$yr, input$myr)
       & povline == (input$pl)]
  
  return(DQ)
  
})

```

```{r}
renderPlotly({
  
  if (input$ms == "Poverty Rate") {
    mpr <- DQ()[, max(fgt_D, na.rm = TRUE)]
  
    pr <- 
      ggplot(data = DQ(), 
             aes(
               x = year
             )) +
        geom_ribbon(aes(ymin = fgt_G, 
                        ymax = fgt_B),
                    fill = "#69b3a2") +
        geom_line(aes(y = fgt_D), color = "black") +
        geom_line(aes(y = fgt_G), color = "black") +
        geom_line(aes(y = fgt_B), color = "black") +
        scale_y_continuous(
          labels = scales::percent, 
          breaks = seq(0, mpr, .05)
        ) +
        labs(
          y     = "Poverty rate",
          x     = ""
        ) +
        theme_ipsum_rc() +
        theme(
          legend.position = "none"
          )  
  } else {
    pr <- 
      ggplot(data = DQ(), 
             aes(
               x = year
             )) +
        geom_ribbon(aes(ymin = npoor_G, 
                        ymax = npoor_B),
                    fill = "orange") +
        geom_line(aes(y = npoor_D), color = "black") +
        geom_line(aes(y = npoor_G), color = "black") +
        geom_line(aes(y = npoor_B), color = "black") +
        scale_y_continuous(
          labels = addUnits
        ) +
        labs(
          y     = "Number of Poor",
          x     = ""
        ) +
        theme_ipsum_rc() +
        theme(
          legend.position = "none"
          )  
  }
  
  ggplotly(pr, tooltip =  "text")
  # ggplotly(pr, tooltip =  "text")

})
```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Explanation of the chart

```{r}
h3("Range of Scenarios in poverty projections")

p("We have three scenarios. First, ", strong("precovid"), " refers to the old scenario before the COVID pandemic hit the world. The ", strong("baseline"), " scenario assumes that the outbreak remains at levels currently expected and that activity recovers later this year. Finally, the ", strong("downside"), " scenario assumes that outbreaks persist longer than expected, forcing lockdown measures to be maintained or reintroduced. Should the downside scenario materialize, vulnerable firms would exit markets, vulnerable households would sharply reduce consumption, and several low- and middle-income countries would see heightened financial stress.")

p("You can also select a different poverty line or change the poverty rate for number of poor")

```

> this is some text

