---
title: "Inequality between countries"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    theme: paper
    source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library("here")
library("data.table")
library("ggplot2")
library("plotly")
library("purrr")

#----------------------------------------------------------
#   subfunctions
#----------------------------------------------------------
# source(here("R", "utils.R"))


qtile <- function(x) {
  nq  <- 10
  N   <-  length(x)
  csw <-  1:N
  qp  <-   floor(csw/((N+1)/nq)) + 1
  return(qp)
}

# calculation of ratios
ratio_calc <- function(DT,
                       nm, 
                       dn, 
                       pc   = 50, 
                       ms   = mean,
                       yrs  = c(1993, 2017)
                       ) {
  
  calc <- paste0(".(", ms, "  = ", ms, "(pv, na.rm = TRUE))")
  calc <- parse(text = calc)
  
  
  nmp <- ord_nums( unique(nm) ) 
  dnp <- ord_nums( unique(dn) ) 

  
  
  DW <- DT[
    # Filter selected percentile
    goal == pc
    & year  %in% yrs
    
    ][
      # classify numerator and denominator
      ,
      gr := ifelse(qp %between% nm, "nm",
                   ifelse(qp %between% dn, "dn", NA_character_ )
      )
      
    ][
      # remove not necessary data
      !is.na(gr)
    ][
      , # Make requested calculation
      eval(calc),
      by = .(year, goal, gr)
    ][
      ,
      label := paste0(paste(nmp, collapse = "-"), "/", paste(dnp, collapse = "-"))
    ]
  
  # Reshape to wide
  DW <- dcast.data.table(DW,
              year + label ~ gr,
              value.var = ms)
  
  # Ratio
  DW[
    ,
      ratio := round(nm/dn, digits = 2)
    ]
  
  return(DW)

}



# Ordinal numbers
ord_nums <- function(n){
  
  ord <- ifelse(n %in% c(11,12,13),  "th",
                ifelse(
                  n %% 10 == 1, 'st',
                  ifelse(
                    n %% 10 == 2, 'nd',
                    ifelse(
                      n %% 10 == 3 , 'rd',  "th"
                    )
                  )
                )
          )
  
  return(paste0(n, ord))
}


#----------------------------------------------------------
#   Aux data
#----------------------------------------------------------
cr  <- readr::read_rds(here("data", "cty_regs_names.rds"))
dfc <- readr::read_rds(here("data", "dfc.rds"))


#----------------------------------------------------------
#   Calculate Quantiles
#----------------------------------------------------------

# set data.table

DT <- as.data.table(dfc)
cr <- as.data.table(cr)
setnames(DT, "threshold", "pv")


# Sort
setorder(DT, year, goal, pv)

DT <- DT[
  # remove old years
  year >= 1990
  ][,
  # multiply by 100
  goal := 100*goal
  
  ][
  ,# Create deciles in each percentile
  qp := qtile(pv),
  by = .(year, goal)
  
  ][
    ,
    headcount := NULL
  ][
    # Merge country names and regions
    cr, 
    on = .(countrycode)
    ]


yrs <- DT[, unique(year)]

```

Ratios to selected deciles and Densities
===========================================================


Sidebar {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r}
sliderInput("pc", 
            label = "Percentile",
            min = 10, max = 100, value = 50, step = 10)

sliderInput("qps", 
            label = "Decile within percentiles",
            min = 1, max = 10, value = 1, step = 1)

sliderInput("mrt", 
            label = "Max decile",
            min = 1, max = 10, value = 10, step = 1)

checkboxInput("log2_x", 
              label = "show X-axis in log2",  
              value = FALSE)

checkboxInput("log2_y", 
              label = "show Y-axis in log2",  
              value = FALSE)

selectInput("yr", 
            label    = "Years",
            choices  = yrs, 
            selected = c(1993, 2002, 2010, 2015, 2017), 
            multiple = TRUE)

selectInput("ms", 
            label = "Measure:",
            choices = c("sum", "mean", "min", "max"),
            selected = "sum")

sliderInput("nm", 
            label = "Decile within percentile (Numerator):",
            min = 1, max = 10, value = c(8,9), step = 1)

sliderInput("dn", 
            label = "Decile within percentile (Denominator):",
            min = 1, max = 10, value = c(1,4), step = 1)





```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Normalized Deciles

```{r}

DTF <- reactive({
  DTF <- 
    DT[
    qp == input$qps 
    & goal == input$pc
    & year  %in% input$yr
    ][
      ,
      .SD[which.max(pv)],
      by = .(year)
    ]
  setorder(DTF, year, pv)
})
  

DG <- reactive({
  DG <- 
    DT[
     goal == input$pc 
     & !is.na(pv) 
     & year  %in% input$yr
     & qp <= input$mrt
     ][
      DTF(),
      on = .(year),
      pvd := i.pv
      ][
        ,
        ratio := pv/pvd
      ][,
        N := .N,
        by = .(year)
      ]
    
  setorder(DG, year, pv)
  
  DG[
    ,
    i := rowid(year)
    ][
      ,
      rpos := i/N
    ][
        , # Create Text variable
        text := paste0("Country: ",    countryname,"-",coverage, "\n",
                       "Data type: ",  datatype, "\n",
                       "Year: ",       year, "\n",
                       "Percentile: ", round(rpos*100, digits = 2), "\n",
                       "Ratio:",       round(ratio, digits = 2), "\n")
      ]

})
```

```{r}
renderPlotly({
  pn <- ggplot(DG(),
       aes(
         x = rpos,
         y = ratio,
         color = factor(year)
       )
       ) +
  geom_line() +
  geom_point(aes( 
         text = text)) +
  theme_minimal() + 
    labs(
      title = "Evolution of inequality across countries ",
      x     = "Relative position of country (percentile)",
      y     = "Ratio percentile/selected decile", 
      color = "Year"
    )
  
  if (input$log2_x == TRUE) {
    pn <- pn + 
      scale_x_continuous(trans = 'log2')
  }
  
  if (input$log2_y == TRUE) {
    pn <- pn + 
      scale_y_continuous(trans = 'log2')
  }
  
  ggplotly(pn, tooltip = "text")
})
```


### Density over time of percentile 
```{r}
renderPlotly({
  
  pd <- ggplot(DG(),
       aes(x = pv,
           fill  = factor(year)
       )
    ) +
    geom_density(alpha = .2)+
    theme_minimal() +
    labs(x = "Distribution of medians over time") +
    theme(
      legend.title = element_blank(),
      legend.position = c(.8, .5),
      legend.direction = "horizontal"
    )
  
  ggplotly(pd)
   
})

```




Row
-----------------------------------------------------------------------

### Evolution of ratio 

```{r}

DF <- reactive({
  
  # calculation
  
  calc <- paste0(".(", input$ms, "  = ", input$ms, "(pv, na.rm = TRUE))")
  calc <- parse(text = calc)
  
  
  DW <- DT[
    # Filter selected percentile
    goal == input$pc 
    & !is.na(pv) 
    & year  %in% input$yr
  
    ][
    # classify numerator and denominator
    ,
    gr := ifelse(qp %between% input$nm, "nm",
                 ifelse(qp %between% input$dn, "dn", NA_character_ )
                 )
  
    ][
    # remove not necessary data
    !is.na(gr)
    ][
      , # Make requested calculation
      eval(calc),
      by = .(year, goal, gr)
    ]
  
  # Reshape to wide
  DW <- dcast.data.table(DW,
              year ~ gr,
              value.var = input$ms)
  
  # Ratio
  DW[
    ,
    ratio := round(nm/dn, digits = 2)
    ]

})


renderPlotly({
 pr <- ggplot(DF(),
         aes(
           x = year,
           y = ratio)
         )+
    geom_point() +
    geom_line() +
    theme_minimal() +
    labs(y = "Evolution of ratio") +
    theme(
      legend.title = element_blank()
    )
  
  ggplotly(pr)

})





```


Evolution of defined ratios
===========================================================


Sidebar {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r}

sliderInput("pc2", 
            label = "Percentile",
            min = 10, max = 100, value = 50, step = 10)

selectInput("yrs2", 
            label    = "Years",
            choices  = yrs, 
            selected = c(1993, 2017), 
            multiple = TRUE)

selectInput("ms2", 
            label = "Measure:",
            choices = c("sum", "mean", "min", "max"),
            selected = "sum")
```

*Please select the corresponding numerators and denominator of the ratios*

```{r}

sliderInput("nm1", 
            label = "Numerator1:",
            min = 1, max = 10, value = c(9,9), step = 1)

sliderInput("dn1", 
            label = "Denominator1:",
            min = 1, max = 10, value = c(1,1), step = 1)

sliderInput("nm2", 
            label = "Numerator2:",
            min = 1, max = 10, value = c(8,8), step = 1)

sliderInput("dn2", 
            label = "Denominator2:",
            min = 1, max = 10, value = c(2,2), step = 1)

sliderInput("nm3", 
            label = "Numerator3:",
            min = 1, max = 10, value = c(7,7), step = 1)

sliderInput("dn3", 
            label = "Denominator3:",
            min = 1, max = 10, value = c(3,3), step = 1)

sliderInput("nm4", 
            label = "Numerator4:",
            min = 1, max = 10, value = c(6,6), step = 1)

sliderInput("dn4", 
            label = "Denominator4:",
            min = 1, max = 10, value = c(4,4), step = 1)

```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Inequality Ratios

```{r}
LF <- reactive({

rc_args <-
        list(
          nm = list(
            input$nm1,
            input$nm2,
            input$nm3,
            input$nm4
            ),
          dn = list(
            input$dn1,
            input$dn2,
            input$dn3,
            input$dn4
          )
        )

  LF <-  pmap_df(rc_args, ratio_calc, 
          pc  = input$pc2, 
          ms  = input$ms2, 
          yrs = input$yrs2, 
          DT = DT)
  
  return(LF)
})

```

```{r}
renderPlotly({
  prt <- ggplot(LF(), 
          aes(
            x     = factor(label), 
            y     = ratio,
            color = factor(year), 
            group = factor(year)
            )
          ) +
          geom_line() +
          geom_point() +
          theme_minimal() +
    labs(
      title = "Inequality Ratios", 
      x     = "Numerators/Denominators",
      y     = "Ratio",
      color = "Year"
    )
        

  
  ggplotly(prt)
})
```






