---
title: "Bottom 40 story"
output:
  xaringan::moon_reader:
    seal: false
    css: ["css/sfah.css", "css/fonts.css", "default"]
    self_contained: false
    lib_dir: libs
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
      ratio: "16:9"
      titleSlideClass: ["left", "middle", "inverse"]
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(knitr)
library(scales)
library(ggpubr)
library(xaringanthemer)
library(here)

knitr::opts_chunk$set(
  warning = FALSE,
  collapse = TRUE,
  message = FALSE,
  echo = FALSE,
  fig.retina = 3,
  fig.width = 10
)

# options(knitr.table.format = "html")
library(fontawesome) # from github: https://github.com/rstudio/fontawesome
xaringanExtra::use_xaringan_extra(c("tile_view", "animate_css", "tachyons"))
```

class: inverse, right, bottom
## Bottom 40

## A changing story

???
Intcomments
```{r initcal}
if (length(ls(pattern = "ld_b40_1")) == 0 ) { # load data?
  source(here("R", "SDG_10_Growth40_2017rep_AC.R"))
  ld_b40_1 <-  1
}

b40chart <- function(data, ...) {

  df <- data %>%
    filter(...) %>%
    arrange(ordervar, sortvar ) %>%
    mutate(
      cty = factor(country, levels = country)
    )

  p <- ggplot(data = df,
              aes(y = cty)) +
    theme_minimal() +
    theme(
      axis.text.y       = element_text(size = 5),
      axis.title.y      = element_blank(),
      strip.text.y.left = element_text(size = 7)
    ) +
    labs(
      title               = "Growth Bottom 40 vs National Average",
      subtitle            = "Sorted by top countries",
      caption             = "Bottom and Total growth as reported in the Global Database of Share Prosperity.",
      x                   = "Growth",
      y                   = ""
    ) +
    geom_vline(
      xintercept          = 0,
      color               = "red",
      linetype            = "dashed"
    )  +
    facet_grid(
      incomegroup ~ .,
      scales              = "free",
      space               = "free",
      switch              = "y"
    )
  return(p)
}


```
---
.left-column[

]
.right-column[
```{r b401}
ggplot(data,
            aes(y = id)) +
  geom_segment(aes(
    yend = id,
    x = Growth40,
    xend = Growth
  ),
  color = rgb(0, 0, 0, 0.3)
  ) +
  geom_point(
    aes(x = Growth, text = country),
    color = "black",
    fill = "white",
    shape = 21,
    stroke = 0.7,
    size = 2
  )
```
]

